# Generated by Django 5.0.6 on 2026-05-03 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='variantoption',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.variantattribute'),
        ),
        migrations.AddField(
            model_name='productvariantoption',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.variantoption'),
        ),
        migrations.AlterUniqueTogether(
            name='productspec',
            unique_together={('product', 'spec_key')},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'product', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='variantoption',
            unique_together={('attribute', 'label')},
        ),
        migrations.AlterUniqueTogether(
            name='productvariantoption',
            unique_together={('variant', 'option')},
        ),
    ]
